import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
# Your code starts here
st.markdown("""
This Streamlit application, 'XAI for LLMs', provides an interactive exploration of Explainable AI (XAI) concepts and techniques applied to Large Language Models (LLMs), leveraging synthetic data to simulate real-world scenarios. Users can generate synthetic LLM interaction data, explore core XAI concepts like interpretability vs. transparency, simulate saliency maps and counterfactual explanations, and analyze key visualizations related to explanation quality, faithfulness, and token influence. The application aims to enhance understanding of how to make LLM decisions more transparent and interpretable.
""")

page = st.sidebar.selectbox(label="Navigation", options=["XAI for LLMs"])
if page == "XAI for LLMs":
    from application_pages.xai_for_llms import main
    main()
# Your code ends here

# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
